### ISSUE TITLE
[OTHER] Weird cron time

### ISSUE THREAD

**Issue by Bashamega** [eddiejaoude/github-trending-repos#20]
### What would you like to share?

Hello:)

While reviewing the code i thought that is is weird that the cron job runs everyday at 08:10 AM.
I think it will be better to round it up to 00:00 Am

**Comment by eddiejaoude** [comment]
It is not clear when GitHub refreshes the Trending page, just in case it is PDT which is UTC-7, I thought it would be best to only collect the data at 8am. Otherwise we could end up with incorrect data.
