### ISSUE TITLE
[FEATURE] Display the last fetched data for daily

### ISSUE THREAD

**Issue by Bashamega** [eddiejaoude/github-trending-repos#21]
### Description

Data is collect at 8am UTC to make sure we have today's new data, as we don't know when GitHub releases the new trending data.

If visiting the root of the project `/` before 8am UTC, there is no data for today, we should display the latest data.

**Comment by Bashamega** [comment]
I would like to work on this @eddiejaoude

**Comment by eddiejaoude** [comment]
Sure, assigned to you @Bashamega
