### ISSUE TITLE
Cors Errors

### ISSUE THREAD

**Issue by Bashamega** [eddiejaoude/github-trending-repos#22]
### Description

Hello:)

I was trying to fetch the api, but it seems that the api has cors restrictions. Can you remove the restrictions or tell me how i should use the api without getting blocked?

### Screenshots

![image](https://github.com/user-attachments/assets/68c41f26-7d48-4499-9541-04a3f101bedb)

**Comment by eddiejaoude** [comment]
Ah yes we need to enable CORS for all access, here are the NestJS docs https://docs.nestjs.com/security/cors
