### ISSUE TITLE
The old data is loading today's data

### ISSUE THREAD

**Issue by Bashamega** [eddiejaoude/github-trending-repos#25]
### Description

Hello:)

When I try to fetch an older day is just loads today. 
For example:
https://trending.eddiehubcommunity.org/daily?2024-09-12
Is the same as today.

**Comment by Bashamega** [comment]
The correct link should be: https://trending.eddiehubcommunity.org/daily?date=2024-09-12. We need to fix the readme

**Comment by eddiejaoude** [comment]
YES! Thank you! 🎉
